services:  
  flowise-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev_access_secret_key_change_this_in_production}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-${JWT_SECRET_KEY:-dev_access_secret_key_change_this_in_production}}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-${JWT_SECRET_KEY:-dev_refresh_secret_key_change_this_in_production}}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=24
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=${JWT_REFRESH_TOKEN_EXPIRE_DAYS:-7}
      - FLOWISE_API_URL=${FLOWISE_API_URL:-http://flowise:3000}
      - FLOWISE_API_KEY=${FLOWISE_API_KEY}
      - EXTERNAL_AUTH_URL=${EXTERNAL_AUTH_URL:-http://auth-service:8001}
      - ACCOUNTING_SERVICE_URL=${ACCOUNTING_SERVICE_URL:-http://accounting-service:8002}
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE_NAME=flowise_proxy
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - mongodb
    networks:
      - flowise-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:7-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=s3cr3t_p@ssw0rdds_!@#$
      - MONGO_INITDB_DATABASE=flowise_proxy
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo-prod.js:/docker-entrypoint-initdb.d/init-mongo-prod.js:ro
    networks:
      - flowise-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "27020:27017"

volumes:
  mongodb_data:
    driver: local

networks:
  flowise-network:
    driver: bridge
