version: '3.8'

services:
  accounting-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=accounting_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_ACCESS_SECRET=dev_access_secret_key_change_this_in_production
      - JWT_REFRESH_SECRET=dev_refresh_secret_key_change_this_in_production
      - LOG_LEVEL=debug
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - accounting-network
      - chatbot-shared-network
    restart: always

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=accounting_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - accounting-network
    restart: always

networks:
  accounting-network:
    driver: bridge
  chatbot-shared-network:
    external: true

volumes:
  postgres-data: